# ChirpStack Fuota SMPTransport configuration
[chirpstack]
server_addr = "54.166.56.164:8080"
api_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjY1ZmY2NTRlLTVhYTgtNGFjMy1iMTdmLTExZDlmMjJmMmUxYyIsInR5cCI6ImtleSJ9.fxBsg5OwReTC2rQihYn-s8HCfRXE_aCKdrcsple-wvM"

[fuota]
server_addr = "54.166.56.164:8070"
# The app_id with which the devices are associated
app_id = "28c978af-212a-4e48-87af-b4655e650b79"
# The list of dev_eui, gen_app_key pairs to send the firmware chunks to
# [{dev_eui = "", gen_app_key = ""}, ...]
deployment_devices = [{dev_eui="029a64fe73a5069a", gen_app_key="d8548200000000000000000000000001"}]

downlink_speed = "DL_SLOW"
multicast_group_type = "CLASS_C"

[tas]
# Needed to get (unicast) uplink messages from the chirpstack connected devices
server_addr = "http://54.166.56.164:8002"
lns_id = "aea1f3d6-bc17-4162-b5c1-ddf71c8811ed"

